### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by Untit1ed** [neris/NGettext#1]
Any plans for making a nuget package for this great tool?

**Comment by NinZine** [comment]
This is definitely the best Gettext tool for .NET out there. Agree on making a NuGet package for ease of access. :)

**Comment by stukdev** [comment]
Is released the package?

**Comment by neris** [comment]
Sorry for the long wait (more than a year omg!). I had a big lack of time.
NuGet package released: https://www.nuget.org/packages/NGettext/
