### ISSUE TITLE
How to add cultures

### ISSUE THREAD

**Issue by pdfforge** [neris/NGettext#14]
We are currently evaluating NGettext and are in the need to add cultures that are not defined in .Net itself, especially "Gaelic (Scotland)" (iso code "gla") and "Catalan (Valencia)" (iso code ca, but the language is different from Catalonian Catalan, which also has "ca").

As there is no easy way to add new CultureInfo instances (this requires admin privileges), what would be an alternative to allow this inside an application?

Would you be open for a pull request that replaces the usage of CultureInfo with something we can populate ourselves? (while maintain API compatibility and keep calls with CultureInfo)

Or is there an easier way to achieve this?

**Comment by neris** [comment]
Well… Here's a couple of suggestions:

If you just want to use different texts for those cultures, you can simply load translation files directly and specify the nearest CultureInfo for Catalog for plural rules and string formatting.
```csharp
var catalog = new Catalog(translationFileStream, nearestCultureInfo);
```

If you want to use different plural rules for those cultures too, you can either use NGettext.PluralCompile package to parse plural rules from *.mo files, or build them by yourself.

**Comment by pdfforge** [comment]
Thank you for the quick reply. I think that we will load the mo files directly then, as we have a good similar culture there.
