### ISSUE TITLE
Catalog path confussion

### ISSUE THREAD

**Issue by HolyOne** [neris/NGettext#16]
I am trying to use NGetText using T.cs and suggested Catalog loading code

Here is what I use to load a mo file
 public static readonly ICatalog _Catalog = new Catalog("MyTestWebsite",  "./locale");

I can't get the translated string from GetText function. So I am most probably pointing to some wrong location.

My problem is the same line just works the same way if I use a random string instead of MyTestWebsite. It should throw an exception if that file does not exist.  And I see no filename when I debug into that variable. 

So I am not sure what file it is trying to load, is it /bin/locale/... ? is it /locale/.... ? or is it trying to load the file from another directory?

**Comment by neris** [comment]
`new Catalog("MyTestWebsite", "./locale")` will try to load translation file from `<CurrentApplicationWorkingDirectory>/locale/<CurrentUICulture>/LC_MESSAGES/Example.mo`.
You can find out what is the working directory by calling the `System.IO.Directory.GetCurrentDirectory()` method. Or you can specify a different path to your locale folder instead of `./locale`.

**Comment by mwpowellhtx** [comment]
Follow on question, I'm sure there is an historical precedent for the `LC_MESSAGES` path and so forth, would you mind clarifying that please? Not trying to be an L10N expert myself, but a little more in depth insight would be helpful.

Also, are these MO thingies loaded as file? Or may they be embedded as resources?

Lastly, sort of tangent to the actual assets themselves, it is possible to contain different L10N contexts using the `Catalog` `DomainName`, correct? For instance, in WPF, if we wanted to localize a `Window` apart from a `Control` or perhaps an `Enum` with `DisplayAttribute` annotation, along these lines.

**Comment by VitaliiTsilnyk** [comment]
> Follow on question, I'm sure there is an historical precedent for the `LC_MESSAGES` path and so forth, would you mind clarifying that please? Not trying to be an L10N expert myself, but a little more in depth insight would be helpful.

Yeah it's for historical reasons. This library follows the existing convention of the path to the translation files as any other GNU-based library. But you can easily load the translations from a different path.

> Also, are these MO thingies loaded as file? Or may they be embedded as resources?

There are a bunch of Catalog class constructors that allow you to load the translations from different sources, including a System.Stream, that can point to an embedded resource.

> Lastly, sort of tangent to the actual assets themselves, it is possible to contain different L10N contexts using the `Catalog` `DomainName`, correct? For instance, in WPF, if we wanted to localize a `Window` apart from a `Control` or perhaps an `Enum` with `DisplayAttribute` annotation, along these lines.

Not really sure what you mean, but you can use multiple different catalogs loaded from different files at the same time. Or you can use the `GetParticular*` methods to distinguish translation strings with different contexts.

**Comment by mwpowellhtx** [comment]
I enjoy the flexibility, sounds great, thank you!

> There are a bunch of Catalog class constructors that allow you to load the translations from different sources, including a System.Stream, that can point to an embedded resource.

To clarify, when there is `string localeDir` in the ctor arguments, we must follow the `"LC_MESSAGES"` path.

Or, generically, we may provide a `System.IO.Stream`, which, I presume, may be any valid MO stream, from either `System.IO.FileStream` custom location, or internally, even more generically Stream.IO.Stream, i.e. as provided by `ResourceManager.GetStream`.

Cheers 🍻 again and thank you.
