### ISSUE TITLE
How i can save catalog ?

### ISSUE THREAD

**Issue by ebadola** [neris/NGettext#17]
Hi
I want use  form UI to translate all key
after translating i want know how i can save  after edited ?
thank you

**Comment by neris** [comment]
NGettext does not support translate file modification. It only can read a translation file into memory and provides an API to use translations.
I'd recommend to use [Poedit](https://poedit.net/) to extract strings from the code, translate and compile into a `.mo` file.
Also, there's many alternatives to Poedit, or you can even create a `.po` file (the format is pretty easy) and compile it into `.mo` using `msgfmt` (a utility from the original GNU/Gettext toolkit).
