### ISSUE TITLE
Is there a way to load .po files?

### ISSUE THREAD

**Issue by kruncher** [neris/NGettext#20]
Hey

Just a quick question, is it possible to load the non-compiled .po files? or would this require a custom loader implementation?

Many thanks

**Comment by neris** [comment]
No, we don't have a loader for .po files.
It's a little bit complicated to load such files, especially when it comes to encoding detection.

**Comment by kruncher** [comment]
Thanks for the fast response! Yeah I can imagine how that would be complicated.

**Comment by Sigvaard** [comment]
> As is usual with text formats, immediately something must be said about the text encoding of a PO file. While you could use encodings other than UTF-8 if no non-ASCII letters are used in the original text, you really should use UTF-8. The encoding is specified within the PO file itself, and by default it is UTF-8; if you want to use another encoding, you must specify it in the PO header (described later).
