### ISSUE TITLE
Question: Support for translation of strings with more than one plural?

### ISSUE THREAD

**Issue by davidghalls** [neris/NGettext#23]
Is there consideration for support for the translation of statements that contain multiple plurals? I have looked at the docs and interface and I don't see such, unless I missed it. For example, a statement such as:

"Your payment plan requires _n_ payments each month for the next _i_ years."

Thanks for this project, great work!

**Comment by neris** [comment]
No, there is no option for that and I don't think there will be one in the future.
This library is an implementation of the original GNU/Gettext library and it's highly dependent on its interface and format to be able to use all the great tools and services built around GNU/Gettext like Poedit. There's no option for multiple plural triggers in a single string in GNU/Gettext nor in any or the tools for it. It would make the translation file format (and the translation process) much more complicated.

What I would recommend to you is to either split the text into two sentences or extract a portion of it into another translation string like this:
```c-sharp
var periodText = catalog.GetPluralString("one year", "{0} years", i, i);
catalog.GetPluralString("Your payment plan requires {0} payment each month for the next {1}.", "Your payment plan requires {0} payments each month for the next {1}.", n, n, periodText);
```

**Comment by davidghalls** [comment]
Thanks for the quick follow up and work-around suggestion.
