### ISSUE TITLE
Does *.po/*.mo files embeding into assymbly on build?

### ISSUE THREAD

**Issue by GLeBaTi** [neris/NGettext#24]
subj

**Comment by neris** [comment]
No, this library provides only the runtime part. You have to extract strings and compile mo files by yourself (you can do it very easily with tools like Poedit, you can find how to do it in the readme).
Then you can embed your resulting mo files into assembly resources (or even place them somewhere outside) and load during the startup of your app.
It's up to yo where to store the file and how to load it. The library provides a convenient interface to load translation files from a filesystem or from a stream.

**Comment by GLeBaTi** [comment]
Thanks for reply
