### ISSUE TITLE
Nuget error ('NGettext' already has a dependency defined)

### ISSUE THREAD

**Issue by jeusdi** [neris/NGettext#5]
I've just created a simple empty dll project. When I add nuget reference it tells me:

`'NGettext' already has a dependency defined for 'Microsoft.CSharp'.`

**Comment by neris** [comment]
What Visual Studio version are you using?

**Comment by jeusdi** [comment]
VS2013

**Comment by neris** [comment]
It seems like you have an outdated NuGet Package Manager.
What version currently installed in your Visual Studio (Tools menu → Extensions and Updates...)?
Try to update it and then reinstall NGettext package.

**Comment by jeusdi** [comment]
Solved.

**Comment by zipgenius** [comment]
Hello. I'm sorry for re-opening this issue but I met the same problem within MonoDevelop 5.10 (where NuGet add-in uses NuGet 2.8.1 and no later release is available).
What can I do?

**Comment by neris** [comment]
@zipgenius You can try standalone [NuGet CLI](https://docs.nuget.org/ndocs/guides/install-nuget#nuget-cli). It works fine on Mono.  
Another option is to manually download and unzip library files from NuGet package and manually add them to project references.

**Comment by zipgenius** [comment]
Thank you very much, it worked fine. I used NuGet CLI.
