### ISSUE TITLE
Initialize Catalog's T class

### ISSUE THREAD

**Issue by jeusdi** [neris/NGettext#6]
How Could I set a culture on private `_catalog` property of `T` class?
How to change it at runtime?

**Comment by neris** [comment]
T class (in the `doc/examples/T.cs` file) is just an example of how you can use NGettext in your application to get some short syntax. It uses CurrentUICulture. If you need to change culture at runtime, you need to implement your own logic for it.

For example you can write something like this:
```csharp
public static void ChangeLocale(CultureInfo cultureInfo)
{
	_Catalog = new Catalog("Example", "./locale", cultureInfo);
}
```
