### ISSUE TITLE
Can't no longer build for Xamarin

### ISSUE THREAD

**Issue by NinZine** [neris/NGettext#8]
Using this library with Mono and Xamarin.iOS/Android, since ddcd8a2 removed the project files with the DNX upgrade. Which in turn makes it not cross-platform.

**Comment by neris** [comment]
You don't need to compile NGettext source to make it work with your project. Just use [NuGet](https://www.nuget.org) to install the [NGettext](https://www.nuget.org/packages/NGettext/) package dependency into your project.

NuGet is cross-platform, it has a CLI tool and can run on Mono too. It can automatically download the package, unpack it, choose the right assembly file for your project and link it into your project references.
As far as I can see, Xamarin Studio [supports](https://blog.xamarin.com/xamarin-studio-and-nuget/) NuGet.

No need to include NGettext's source code project and compile it every time you build your application.
Starting specified commit, NGettext's source code projects intended to be only for NGettext's development and supports only [DNX](https://docs.asp.net/en/latest/dnx/overview.html) (which in it's turn is cross-platform too).

**Comment by NinZine** [comment]
Thanks neris for such an elaborate answer. Definitely support NGettext being able via NuGet cross-platform, it's great.

When I tried to add it to a iOS project via NuGet the following error occurred:

```
Could not install package 'NGettext 0.5.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by neris** [comment]
OK I made PCL version of this library. It should work with Xamarin.ios.
Please try to install it: https://www.nuget.org/packages/NGettext/0.5.1-beta1
This is prerelase package so you may need to enable prerelease package search in your NuGet GUI.

**Comment by NinZine** [comment]
Confirmed working! Used `Install-Package Ngettext -Pre` with Xamarin Package Console Extension.

**Comment by neris** [comment]
Great! Thank you for your feedback.
